ibtikar_share_economy_payfort_request_sdk_token:
    path:     /request-sdk-token/{device_id}
    defaults: { _controller: IbtikarShareEconomyPayFortBundle:API/PayFort:requestSDKToken }

ibtikar_share_economy_payfort_add_payment_method:
    path:     /auth/payment-methods/add
    defaults: { _controller: IbtikarShareEconomyPayFortBundle:API/PayFort:addPaymentMethod }
    methods:  POST